export const GROUP_MATCHES_SCHEDULE: Record<string, {home: string, away: string, date: string, time: string, location: string}[]> = {
  'A': [
    { home: 'MEX', away: 'ZAF', date: '11/06 (Qui)', time: 'TBD', location: 'Cidade do México' },
    { home: 'KOR', away: 'CZE', date: '11/06 (Qui)', time: 'TBD', location: 'Guadalajara' },
    { home: 'CZE', away: 'ZAF', date: '18/06 (Qui)', time: '13:00', location: 'Atlanta' },
    { home: 'MEX', away: 'KOR', date: '18/06 (Qui)', time: '22:00', location: 'Guadalajara' },
    { home: 'CZE', away: 'MEX', date: '24/06 (Qua)', time: '22:00', location: 'Cidade do México' },
    { home: 'ZAF', away: 'KOR', date: '24/06 (Qua)', time: '22:00', location: 'Guadalajara' },
  ],
  'B': [
    { home: 'CAN', away: 'BIH', date: '12/06 (Sex)', time: 'TBD', location: 'Toronto' },
    { home: 'QAT', away: 'CHE', date: '13/06 (Sáb)', time: 'TBD', location: 'Santa Clara' },
    { home: 'CHE', away: 'BIH', date: '18/06 (Qui)', time: '16:00', location: 'Inglewood' },
    { home: 'CAN', away: 'QAT', date: '18/06 (Qui)', time: '19:00', location: 'Vancouver' },
    { home: 'CHE', away: 'CAN', date: '24/06 (Qua)', time: '16:00', location: 'Vancouver' },
    { home: 'BIH', away: 'QAT', date: '24/06 (Qua)', time: '16:00', location: 'Seattle' },
  ],
  'C': [
    { home: 'BRA', away: 'MAR', date: '13/06 (Sáb)', time: 'TBD', location: 'East Rutherford' },
    { home: 'HTI', away: 'SCO', date: '13/06 (Sáb)', time: 'TBD', location: 'Foxborough' },
    { home: 'SCO', away: 'MAR', date: '19/06 (Sex)', time: '19:00', location: 'Foxborough' },
    { home: 'BRA', away: 'HTI', date: '19/06 (Sex)', time: '21:30', location: 'Filadélfia' },
    { home: 'SCO', away: 'BRA', date: '24/06 (Qua)', time: '19:00', location: 'Miami Gardens' },
    { home: 'MAR', away: 'HTI', date: '24/06 (Qua)', time: '19:00', location: 'Atlanta' },
  ],
  'D': [
    { home: 'USA', away: 'PRY', date: '12/06 (Sex)', time: 'TBD', location: 'Inglewood' },
    { home: 'AUS', away: 'TUR', date: '14/06 (Dom)', time: 'TBD', location: 'Vancouver' },
    { home: 'USA', away: 'AUS', date: '19/06 (Sex)', time: '16:00', location: 'Seattle' },
    { home: 'TUR', away: 'PRY', date: '20/06 (Sáb)', time: '00:00', location: 'Santa Clara' },
    { home: 'TUR', away: 'USA', date: '25/06 (Qui)', time: '23:00', location: 'Inglewood' },
    { home: 'PRY', away: 'AUS', date: '25/06 (Qui)', time: '23:00', location: 'Santa Clara' },
  ],
  'E': [
    { home: 'DEU', away: 'CUW', date: '14/06 (Dom)', time: '14:00', location: 'Houston' },
    { home: 'CIV', away: 'ECU', date: '14/06 (Dom)', time: '20:00', location: 'Filadélfia' },
    { home: 'DEU', away: 'CIV', date: '20/06 (Sáb)', time: '17:00', location: 'Toronto' },
    { home: 'ECU', away: 'CUW', date: '20/06 (Sáb)', time: '21:00', location: 'Kansas City' },
    { home: 'ECU', away: 'DEU', date: '25/06 (Qui)', time: '17:00', location: 'East Rutherford' },
    { home: 'CUW', away: 'CIV', date: '25/06 (Qui)', time: '17:00', location: 'Filadélfia' },
  ],
  'F': [
    { home: 'NLD', away: 'JPN', date: '14/06 (Dom)', time: '17:00', location: 'Arlington' },
    { home: 'SWE', away: 'TUN', date: '14/06 (Dom)', time: '23:00', location: 'Guadalupe' },
    { home: 'NLD', away: 'SWE', date: '20/06 (Sáb)', time: '14:00', location: 'Houston' },
    { home: 'TUN', away: 'JPN', date: '21/06 (Dom)', time: '01:00', location: 'Guadalupe' },
    { home: 'JPN', away: 'SWE', date: '25/06 (Qui)', time: '20:00', location: 'Arlington' },
    { home: 'TUN', away: 'NLD', date: '25/06 (Qui)', time: '20:00', location: 'Kansas City' },
  ],
  'G': [
    { home: 'BEL', away: 'EGY', date: '15/06 (Seg)', time: '16:00', location: 'Seattle' },
    { home: 'IRN', away: 'NZL', date: '15/06 (Seg)', time: '22:00', location: 'Inglewood' },
    { home: 'BEL', away: 'IRN', date: '21/06 (Dom)', time: '16:00', location: 'Inglewood' },
    { home: 'NZL', away: 'EGY', date: '22/06 (Seg)', time: '22:00', location: 'Vancouver' },
    { home: 'EGY', away: 'IRN', date: '27/06 (Sáb)', time: '00:00', location: 'Seattle' },
    { home: 'NZL', away: 'BEL', date: '27/06 (Sáb)', time: '00:00', location: 'Vancouver' },
  ],
  'H': [
    { home: 'ESP', away: 'CPV', date: '15/06 (Seg)', time: '13:00', location: 'Atlanta' },
    { home: 'SAU', away: 'URY', date: '15/06 (Seg)', time: '19:00', location: 'Miami Gardens' },
    { home: 'ESP', away: 'SAU', date: '21/06 (Dom)', time: '13:00', location: 'Atlanta' },
    { home: 'URY', away: 'CPV', date: '21/06 (Dom)', time: '19:00', location: 'Miami Gardens' },
    { home: 'CPV', away: 'SAU', date: '26/06 (Sex)', time: '21:00', location: 'Houston' },
    { home: 'URY', away: 'ESP', date: '26/06 (Sex)', time: '21:00', location: 'Guadalajara' },
  ],
  'I': [
    { home: 'FRA', away: 'SEN', date: '16/06 (Ter)', time: '16:00', location: 'East Rutherford' },
    { home: 'IRQ', away: 'NOR', date: '16/06 (Ter)', time: '19:00', location: 'Boston' },
    { home: 'FRA', away: 'IRQ', date: '22/06 (Seg)', time: '18:00', location: 'Filadélfia' },
    { home: 'NOR', away: 'SEN', date: '22/06 (Seg)', time: '21:00', location: 'East Rutherford' },
    { home: 'NOR', away: 'FRA', date: '26/06 (Sex)', time: '16:00', location: 'Boston' },
    { home: 'SEN', away: 'IRQ', date: '26/06 (Sex)', time: '16:00', location: 'Toronto' },
  ],
  'J': [
    { home: 'ARG', away: 'DZA', date: '16/06 (Ter)', time: '22:00', location: 'Kansas City' },
    { home: 'AUT', away: 'JOR', date: '16/06 (Ter)', time: '23:00', location: 'Santa Clara' },
    { home: 'ARG', away: 'AUT', date: '22/06 (Seg)', time: '13:00', location: 'Arlington' },
    { home: 'JOR', away: 'DZA', date: '22/06 (Seg)', time: '23:00', location: 'Santa Clara' },
    { home: 'DZA', away: 'AUT', date: '27/06 (Sáb)', time: '23:00', location: 'Kansas City' },
    { home: 'JOR', away: 'ARG', date: '27/06 (Sáb)', time: '23:00', location: 'Arlington' },
  ],
  'K': [
    { home: 'PRT', away: 'COD', date: '17/06 (Qua)', time: '14:00', location: 'Houston' },
    { home: 'UZB', away: 'COL', date: '17/06 (Qua)', time: '23:00', location: 'Cidade do México' },
    { home: 'PRT', away: 'UZB', date: '23/06 (Ter)', time: '14:00', location: 'Houston' },
    { home: 'COL', away: 'COD', date: '23/06 (Ter)', time: '23:00', location: 'Guadalajara' },
    { home: 'COL', away: 'PRT', date: '27/06 (Sáb)', time: '20:30', location: 'Miami Gardens' },
    { home: 'COD', away: 'UZB', date: '27/06 (Sáb)', time: '20:30', location: 'Atlanta' },
  ],
  'L': [
    { home: 'ENG', away: 'HRV', date: '17/06 (Qua)', time: '17:00', location: 'Arlington' },
    { home: 'GHA', away: 'PAN', date: '17/06 (Qua)', time: '20:00', location: 'Toronto' },
    { home: 'ENG', away: 'GHA', date: '23/06 (Ter)', time: '17:00', location: 'Boston' },
    { home: 'PAN', away: 'HRV', date: '23/06 (Ter)', time: '20:00', location: 'Toronto' },
    { home: 'PAN', away: 'ENG', date: '27/06 (Sáb)', time: '18:00', location: 'East Rutherford' },
    { home: 'HRV', away: 'GHA', date: '27/06 (Sáb)', time: '18:00', location: 'Filadélfia' },
  ]
};

